# Generated by Django 5.1.7 on 2026-04-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usertb_enhanced_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertb',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent/Stationery'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
