# Generated by Django 5.1.7 on 2026-04-18 19:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usertb_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(help_text='MD5 hash of input data', max_length=64, unique=True)),
                ('doc_type', models.CharField(max_length=50)),
                ('original_content', models.JSONField()),
                ('polished_content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Cache',
                'verbose_name_plural': 'AI Caches',
            },
        ),
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('last_request_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage',
                'verbose_name_plural': 'AI Usages',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
