# Generated by Django 5.1.7 on 2026-04-02 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('QUOTATION', 'Quotation'), ('PROFORMA', 'Proforma Invoice'), ('AFFIDAVIT', 'Affidavit'), ('CONTRACT', 'Personal Contract'), ('EVENT_PROGRAM', 'Event Program'), ('LETTER', 'General Letter'), ('OTHER', 'Other Document')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(help_text='Flexible JSON storage for all document fields')),
                ('is_polished', models.BooleanField(default=False, help_text='Checked if AI has optimized the content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
