# Generated by Django 5.1.7 on 2026-04-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='customer_name',
            field=models.CharField(blank=True, help_text='For agents creating docs for others', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('CV', 'Curriculum Vitae'), ('INVOICE', 'Business Invoice'), ('LETTER', 'General/Official Letter'), ('QUOTATION', 'Quotation'), ('PROFORMA', 'Proforma Invoice'), ('AFFIDAVIT', 'Affidavit'), ('CONTRACT', 'Personal Contract'), ('EVENT_PROGRAM', 'Event Program'), ('OTHER', 'Other Document')], max_length=50),
        ),
    ]
